ipa = {
    "ɤ": "[oo] as in f[oo]t",
    "ɨ": "[i] as in [i]ll",
    "ju": "[u] as in h[u]ge",
    "ja": "[ya] as in [ya]rn",
    "jo": "[yo] as in [yo]del",
    "je": "[ye] as in [ye]s",
    "jev": "[yev] in wh[yev]er",
    "tʰ": "[t] as in [t]all, with a small release of air",
    "tʃʰ": "[ch] as in [ch]alk, with a small release of air",
    "tsʰ": "[ts] as in le[ts], with a small release of air",
    "pʰ": "[p] as in [p]lay, with a small release of air",
    "kʰ": "[k] as in [k]id, with a small release of air",
    "vo": "[vo] as in [vo]te",
    "ʂ": "short [sh] as in [sh]arp",
    "ɕ": "long [sh] as in [sh]eer",
    "f": "[f] as in [face]",
    "ɑ": "[a] as in [a]lso",
    "b": "[b] as in [b]ean",
    "g": "[g] as in [g]reat",
    "d": "[d] as in [d]ark",
    "ɛ": "[e] as in [e]very",
    "v": "[v] as in [v]alue",
    "z": "[z] as in [z]ipper",
    "t": "[t] as in [t]all",
    "i": "[i] as in sk[i]",
    "k": "[k] as in [k]id",
    "l": "[l] as in [l]emon",
    "m": "[m] as in [m]elon",
    "n": "[n] as in [n]obody",
    "ɔ": "[ough] as in [ough]t",
    "o": "[ow] as in l[ow]",
    "p": "[p] as in [p]lay",
    "ʒ": "[z] as in sei[z]ure",
    "r": "[r] as in [r]un, but rolled",
    "s": "[s] as in [s]alt",
    "u": "[u] as in d[u]de",
    "ʁ": "like the French uvular [r]",
    "ʃ": "[sh] as in [sh]ell",
    "ʃt": "[sht] as in [sht]etl",
    "tʃ": "[ch] as in [ch]alk",
    "ts": "[ts] as in ne[ts]",
    "dz": "[ds] as in li[ds]",
    "χ": "hard [ch] as in Lo[ch]",
    "dʒ": "[j] as in [j]am",
    "h": "[h] as in [h]eart",
    "k'": "like [k] as in [k]id but with the throat closed",
    "t'": "like [t] as in [t]all with the throat closed",
    "p'": "like [p] as in [p]lay with the throat closed",
    "q": "like [k] but farther back",
    "q'": "like [k] but farther back, with the throat closed",
    "ts'": "like [ts] as in ne[ts] with the throat closed",
    "tʃ'": "like [ch] as in [ch]ild with the throat closed",
    "w": "[w] as in [w]ater",
    "æ": "[a] as in h[a]t",
    "ə": "[a] as in tun[a]",
    "ʊ": "[u] as in p[u]t",
    "dˤ": "[d] as in [d]ark, but more emphatic",
    "ħ": "whispered [h]",
    "rˤ": "rolled [r], but more emphatic",
    "sˤ": "[s] as in [s]alt, but more emphatic",
    "tˤ": "[t] as in [t]all, but more emphatic",
    "zˤ": "[z] as in [z]ipper, but more emphatic",
    "ʕ": "uvular [r] as a vowel, no English equivalent",
    "ɣ": "uvular [g]",
    "j": "[y] as in [y]arn",
    "ɾ": "[r] as in [r]ed",
    "ev": "[ev] as in [ev]ery",
    "av": "[av]ocado",
    "af": "[awf] as in [awf]ul",
    "ef": "[eff] as in [eff]ort",
    "ŋ": "[ng] as in ri[ng]",
    "mb": "[mb] as in la[mb]",
    "nd": "[nd] as in e[nd]",
    "ks": "[x] as in e[x]tra",
    "ð": "[th] as in [th]is",
    "θ": "[th] as in [th]ing",
    "ɟ": "[gy] as in ma[gy]ar",
    "c": "[cky] as in ba[cky]ard",
    "ʎ": "[lli] as in mi[lli]on",
    "ɲ": "[ñ] as in jalape[ñ]o",
    "ɖʐ": "like [j] as in [j]am, but harder",
    "ʐ": "like [z] in a[z]ure, but harder",
    "tʂ": "soft [ch] sound",
    "tɕ": "hard [ch] sound",
}